# Generated by Django 5.1.2 on 2025-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memomodel',
            name='scale',
            field=models.TextField(blank=True),
        ),
    ]
